name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy Prod
        env:
          API_URL: ${{ vars.API_URL }}
        run: |
          echo "Deploying to PROD"
          echo "URL: $API_URL"
